seed: 0
njobs: 10
n_threads: 36
index: 0
use_mag: False
use_conc: False
ncolors: 0

n_gal: -1
n_gal_prior: -1
n_grid: 100
n_grid_prior: 60

stamp_size: 48

# bfd
weight_sigma: 0.769
weight_n: 4
# prior settings
minSN: 5.
maxSN: 25.
nSample: 10000
priorSigmaStep: 2.0
priorSigmaCutoff: 5.5
priorSigmaBuffer: 1.
noiseFactor: 1.
diff_covariance: False
n_chunk: 10

# output
priorfile: prior
prior_galfile: cat_prior
galfile: cat
pqrfile: pqr
outdir: testdir3

sims_dict:
  bands: i
  epochs_per_band: 1
  layout_type: grid
  gals_kws: {mag: 25.78, half_light_radius: 0.8}
  shear_scene: False
  buff: 0
  g1: 0.02
  g2: 0.0
  psf_type: moffat
  psf_kws: {beta: 3.5, half_light_radius: 0.41, g1: 0.0, g2: 0.0}

noise_sigma: 0.15
template_noise_sigma: 0.0015

run_prior: False
run_catalog: True
run_pqr: True
